#pragma once
#include <opencv2/core/core.hpp>     
#include <opencv2/features2d/features2d.hpp>
#include <opencv2/nonfree/features2d.hpp>
#include <opencv2/nonfree/nonfree.hpp>
#include "opencv/cv.h"
#include "opencv/highgui.h"
#include <fstream>
#include <string.h>
#include <math.h>